# Site settings
title: HenryGao
description: 'HenryGao‘s Blog 这里记录、分享技术'
url: 'https://HenryGaoGH.github.io'
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'HenryGao'

author:
  name: 'HenryGao'
  email: yoyohenrygao@163.com
  # twitter_username: joshgerdes
  facebook_username: HenryGao
  github_username:  github.com/HenryGaoGH
  linkedin_username:  HenryGao

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
